# Generated by Django 3.2.5 on 2023-07-03 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '966453047'. Up to 15 digits allowed.", regex='^\\+?1?\\d{1,15}$')]),
        ),
    ]
