# Generated by Django 3.2.5 on 2023-07-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='building',
        ),
        migrations.RemoveField(
            model_name='address',
            name='district',
        ),
        migrations.RemoveField(
            model_name='address',
            name='province',
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='address'),
        ),
    ]
